language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer self-update
  - composer install --dev

script:
  - wget https://raw.github.com/jrburke/r.js/2.1.8/dist/r.js
  - phpunit --coverage-text
