language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer self-update
  - composer install --dev

script:
  - php vendor/bin/phpcs --standard=PSR2 --ignore=vendor/ --extensions=php . -n -p
  - wget https://raw.github.com/jrburke/r.js/2.1.8/dist/r.js
  - php vendor/bin/phpunit --coverage-text
